### ISSUE TITLE
[Suggestion] Invert tips sort order

### ISSUE THREAD

**Issue by unnamedd** [Luur/SwiftTips#3]
It is more simple to see what is new on the list, if we have the tips in decreasing order. What do you think about this @Luur?

**Comment by Luur** [comment]
Yeah, good idea! I’ll do it ASAP. Thx a lot 😊

**Comment by Luur** [comment]
@unnamedd I've changed list order. Thanks for paying attention 👍

**Comment by unnamedd** [comment]
Great, thank you!!
